# term query
GET http://localhost:9200/books/_search
Content-type:application/json

{
  "query": {
    "terms": {
      "title": [
        "java",
        "python"
      ]
    }
  }
}

###range

GET http://localhost:9200/books/_search
Content-type: application/json

{
  "query": {
    "range": {
      "price": {
        "gt": 50,
        "lt": 70
      }
    }
  }
}

###

###range

GET http://localhost:9200/books/_search
Content-type: application/json

{
  "query": {
    "range": {
      "publish_time": {
        "gt": "2016-01-01",
        "lt": "2016-12-31",
        "format": "yyyy-MM-dd"
      }
    }
  }
}

### exists
GET http://localhost:9200/books/_search
Content-Type: application/json

{
  "query": {
    "exists": {
      "field": "language"
    }
  }
}

### prefix
GET http://localhost:9200/books/_search
Content-Type: application/json

{
  "query": {
    "prefix": {
      "description": "win"
    }
  }
}

### wildcard
GET http://localhost:9200/books/_search
Content-Type: application/json

{
  "query": {
    "wildcard": {
      "author": "张若*"
    }
  }
}

###regexp query
GET http://localhost:9200/_search
Content-Type: application/json

{
  "query": {
    "regexp": {
      "postcode": "w[0-9].+"
    }
  }
}

###fuzzy
GET http://localhost:9200/_search
Content-Type: application/json

{
  "query": {
    "fuzzy": {
      "title": "javascritp"
    }
  }
}

### type
GET http://localhost:9200/_search
Content-Type: application/json

{
  "query": {
    "type": {
      "value": "IT"
    }
  }
}

### ids query
GET http://localhost:9200/_search
Content-Type: application/json

{
  "query": {
    "ids": {
      "type": "IT",
      "values": [
        1,
        2,
        3
      ]
    }
  }
}

### --------------------------复合查询

### constant_score_query
GET http://localhost:9200/_search
Content-Type: application/json

{
  "query": {
    "constant_score": {
      "filter": {
        "term": {
          "title": "java"
        }
      },
      "boost": 1.2
    }
  }
}

### bool

GET http://localhost:9200/_search
Content-Type: application/json

{
  "query": {
    "bool": {
      "minimum_should_match": 1,
      "must": {
        "match": {
          "title": "java"
        }
      },
      "should": [
        {
          "match": {
            "description": "虚"
          }
        }
      ],
      "must_not": {
        "range": {
          "price": {
            "gte": 70
          }
        }
      }
    }
  }
}

### dis_max_query
GET http://localhost:9200/_search
Content-Type: application/json

{
  "query": {
    "dis_max": {
      "tie_breaker": 0.7,
      "boost": 1.2,
      "queries": [
        {
          "term": {
            "description": "虛"
          }
        },
        {
          "term": {
            "title": "java"
          }
        }
      ]
    }
  }
}

### indices
GET http://localhost:9200/_search
Content-Type: application/json

{
  "query": {
    "indices": {
      "indices": [
        "books",
        "books2"
      ],
      "query": {
        "match": {
          "title": "javascript"
        }
      },
      "no_match_query": {
        "term": {
          "title": "basketball"
        }
      }
    }
  }
}

###--------------嵌套
### netsted
PUT http://localhost:9200/my_index
Content-Type: application/json

{
  "mappings": {
    "type1": {
      "properties": {
        "obj1": {
          "type": "nested"
        }
      }
    }
  }
}

### has_child_query

PUT http://localhost:9200/company
Content-Type: application/json

{
  "mappings": {
    "branch": {},
    "employee": {
      "_parent": {
        "type": "branch"
      }
    }
  }
}

###
POST http://localhost:9200/company/branch/_bulk
Content-Type: application/json

//{ "index": { "_id": "london" }}
//{ "name": "London Westminster", "city": "London", "country": "UK" }
//{ "index": { "_id": "liverpool" }}
//{ "name": "Liverpool Central", "city": "Liverpool", "country": "UK" }
//{ "index": { "_id": "paris" }}
//{ "name": "Champs Élysées", "city": "Paris", "country": "France" }

###
PUT http://localhost:9200/company/employee/1?parent=london
Content-Type: application/json

{
  "name": "Alice Smith",
  "dob": "1970-10-24",
  "hobby": "hiking"
}

### 高亮
GET http://localhost:9200/books/_search
Content-Type: application/json

{
  "query": {
    "bool": {
      "must": [
        {
          "term": {
            "title": "javascript"
          }
        },
        {
          "term": {
            "description": "技"
          }
        }
      ]
    }
  },
  "highlight": {
    "fields": {
      "title": {
      },
      "description": {
      }
    }
  }
}

### 排序
GET http://localhost:9200/books/_search
Content-Type: application/json

{
  "query": {
    "match_all": {}
  },
  "sort": [
    {
      "price": {
        "order": "asc"
      }
    },
    {
      "publish_time": {
        "order": "desc"
      }
    }
  ]
}

###
